try {
    let resultado = 10 / 0;
} catch (error) {
    console.log("No puedes dividir entre cero.");
}

//Los bloques try y catch se utilizan para manejar errores en tiempo de ejecuci√≥n.
//Si ocurre un error en el bloque try, el control se traslada al bloque catch correspondiente.